// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuBzM8uNCeU1Twd1R3MXumreqn_7CqNT4',
    appId: '1:57296769818:web:40de73d126f4778c5712a3',
    messagingSenderId: '57296769818',
    projectId: 'reservitta-dev',
    authDomain: 'reservitta-dev.firebaseapp.com',
    storageBucket: 'reservitta-dev.firebasestorage.app',
    measurementId: 'G-3P5CE4QR6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhmSndinWI8r035eH1bEUjTj_4IpEP6p0',
    appId: '1:57296769818:android:2a81866bc0caa4185712a3',
    messagingSenderId: '57296769818',
    projectId: 'reservitta-dev',
    storageBucket: 'reservitta-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRCKvd1lLfKrg54RqZQNGwTH1Nk5wa1Rw',
    appId: '1:57296769818:ios:077a9c964c1b64255712a3',
    messagingSenderId: '57296769818',
    projectId: 'reservitta-dev',
    storageBucket: 'reservitta-dev.firebasestorage.app',
    iosBundleId: 'com.reservitta.reservitta',
  );
}
